AWSTemplateFormatVersion: "2010-09-09"
Description: "Create two Security Groups with specific rules"

Resources:
  SecurityGroup1:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: "Security Group 1 - Allows inbound HTTP and SSH traffic"
      VpcId: !Ref DefaultVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0" # SSH from anywhere
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0" # HTTP from anywhere
      SecurityGroupEgress:
        - IpProtocol: "-1" # Allow all outbound traffic
          CidrIp: "0.0.0.0/0"

  SecurityGroup2:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: "Security Group 2 - Allows inbound HTTPS and MySQL traffic"
      VpcId: !Ref DefaultVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0" # HTTPS from anywhere
        - IpProtocol: "tcp"
          FromPort: 3306
          ToPort: 3306
          CidrIp: "10.0.0.0/16" # MySQL within VPC range
      SecurityGroupEgress:
        - IpProtocol: "-1" # Allow all outbound traffic
          CidrIp: "0.0.0.0/0"

  DefaultVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: "Name"
          Value: "DefaultVPC"

Outputs:
  SG1Id:
    Description: "ID of the first security group"
    Value: !Ref SecurityGroup1

  SG2Id:
    Description: "ID of the second security group"
    Value: !Ref SecurityGroup2
