AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance with a security group.

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allow SSH from anywhere
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allow HTTP from anywhere
      VpcId: !Ref DefaultVpcId

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-00e95a9222311e8ed # Amazon Linux 2 AMI for free tier
      KeyName: MyKeyPair # Replace with your key pair name
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MySimpleEC2Instance

Outputs:
  InstancePublicDNS:
    Description: Public DNS of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicDnsName
  SecurityGroupID:
    Description: Security Group ID
    Value: !Ref MySecurityGroup

Parameters:
  DefaultVpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the EC2 instance will be launched
